const { SlashCommandBuilder } = require("@discordjs/builders");
const { MessageEmbed, Client, CommandInteraction } = require("discord.js");

module.exports = {
    data: new SlashCommandBuilder()
        .setName('generate-invite')
        .setDescription('Generates an invite link for the bot.'),
        /**
         * 
         * @param {Client} client 
         * @param {CommandInteraction} interaction 
         */
    run: async (client, interaction) => {
        try {
            let embed = new MessageEmbed()
            .setAuthor(interaction.user.username, interaction.user.avatarURL())
            .setTitle('Auto Generated Invite Link')
            .setThumbnail(interaction.guild.iconURL({ dynamic: true }))
            .setDescription('Click the link above to invite the bot to your server.')
            .setURL(await client.generateInvite({ scopes: ['bot', 'applications.commands'], permissions: ['ADMINISTRATOR'] }))
            .setTimestamp()
            .setFooter('Generated by using slash command', interaction.user.avatarURL({ dynamic: true }))
            await interaction.followUp({ embeds: [embed] });
        } catch (err) {
            console.error(err);
        }
    }
}